blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Omnixys Community Support
    url: https://github.com/omnixys/omnixys-discussions/discussions
    about: Stelle allgemeine Fragen oder tausche dich mit anderen aus.

issue_templates:
  - name: âœ¨ Profil-Feature Request
    description: Vorschlag fÃ¼r ein neues Feature im Profilmodul
    file: profile_feature_request.yml
    labels: ["enhancement", "profile"]

  - name: ğŸ› Profil-Bug Report
    description: Melde einen Fehler im Profilmodul
    file: profile_bug_report.yml
    labels: ["bug", "needs-triage", "profile"]

  - name: ğŸ” Security Vulnerability
    description: Vertrauliche Meldung einer SicherheitslÃ¼cke
    file: security_vulnerability.yml
    labels: ["security", "confidential"]

  - name: ğŸ™‹ Support-Anfrage
    description: Bitte um Hilfe oder KlÃ¤rung zu Setup, Nutzung oder Konfiguration
    file: profile_support_request.yml
    labels: ["question", "support", "profile"]
